#!/bin/bash
PROVEEDOR=$1
OPCION=$2

FECHA=`date +%Y%m`
MES=`date +%B`
ANIO=`date +%Y`

source /etc/procs/db-conf.sh
MYSQLDB="enlaces"

MYSQLOPTS="--user=$RUSER --password=$RPSS --host=$DBSRV $MYSQLDB"
LOG="/etc/procs/Facturacion/reportes.log"
MYSQLDUMP="/etc/procs/Facturacion/$FECHA-$PROVEEDOR.csv"
q1="/etc/procs/Facturacion/q1.sql"
q2="/etc/procs/Facturacion/q2.sql"
q3="/etc/procs/Facturacion/q3.txt"


print_help(){
echo ""
echo "  Cargos Exinda  1.0 "
echo ""
echo "     Genera los reportes de enlaces para hacer cargos contra la facturacion de Exinda "
echo ""
echo "     Sintaxis: "
echo ""
echo '		genera_facturacion <PROVEEDOR> [<-m>|<-l>]'
echo ""
echo "          <PROVEEDOR>: 	el proveedor del cual deseamos sacar el reporte (MAYUSCULAS)."
echo "		<-m>:		si desea enviar por mail la informacion generada"
echo "		<-l>:		si desea guardar unicamente de modo local la informacion generada"
echo "		"
echo "          Los proveedores validos son :"
echo "                   EXINDA"
echo ""
echo "          Desarrollado por:   Telecomunicaciones"
echo ""

}


genera_reportes(){

echo " Generando  numero de enlaces" 
echo " select count(1) as xx  from enlaces.enlace, enlaces.remoto " > $q1 
echo " where  en_remoto=rm_remoto " >> $q1
echo " and en_estado = 7  and en_tipo_enlace = \"PRI\"  and rm_region > 0  " >>$q1
echo " and en_proveedor in (\"CLARO\", \"NAVEGA\", \"COLUMBUS\", \"TELNOR\") " >> $q1

mysql -h $DBSRV -u $RUSER --password=$RPSS --database=$iMYSQLDB -f --column-names=0 <  $q1  > $q3  
numx="$(cat $q3 | tail -1)"

echo " Generando  calculo para  enlaces" 
echo " select rm_oficinacontable,  " > $q2 
echo " ifnull((select  rm_descripcion from  enlaces.remoto r2 where r2.rm_remoto=r. rm_oficinacontable ), ' ')  as descripcion, " >> $q2 
echo " format(sum(9873 /$numx ),2) as monto_USD$ " >> $q2 
echo " from enlaces.enlace, enlaces.remoto r " >> $q2 
echo " where  en_remoto=rm_remoto " >> $q2 
echo " and en_estado = 7  and en_tipo_enlace = 'PRI'  and rm_region > 0 " >> $q2  
echo " and en_proveedor in ('CLARO', 'NAVEGA', 'COLUMBUS', 'TELNOR') " >> $q2 
echo " group by rm_oficinacontable " >> $q2 

mysql -h $DBSRV -u $RUSER --password=$RPSS  -f  <  $q2  > $MYSQLDUMP  

echo "Report Begin $PROVEEDOR: $date"
echo "MySQL Dump Begin $PROVEEDOR: $date" >> $LOG
cat $MYSQLDUMP >> $LOG
echo "MySQL Dump End $PROVEEDOR: $date" >> $LOG
echo "Report Successful: $date"
}

envio_correo()
{
PROVSUBJECT=$PROVEEDOR
PROVBODY="Se Adjunta Facturacion De $PROVEEDOR"

echo "Enviando correo electronico"
echo "$PROVBODY" \
| mutt -s "Cargos Factura $MES $ANIO : $PROVSUBJECT" \
-a /etc/procs/Facturacion/$FECHA-$PROVEEDOR.csv \
-- facturacion@banrural.com.gt
##-- mario.garcia@banrural.com.gt
}

if [ "$#" -lt 2 ]; then
        print_help
        exit  0
fi


echo "Generando iiii dldll"

if [ "$#" -eq 2 ]; then
	if [ "$OPCION" = "-m" ]; then 
		echo "Generando  mail"
		echo " "
        	genera_reportes
		envio_correo
	fi
        if [ "$OPCION" = "-l" ]; then
                genera_reportes
        fi
        exit  0
fi
